//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// このソース コードは xsd によって自動生成されました。Version=4.0.30319.33440 です。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ArrayOfFlagCondition {
    
    private ArrayOfFlagConditionFlagCondition[] flagConditionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FlagCondition")]
    public ArrayOfFlagConditionFlagCondition[] FlagCondition {
        get {
            return this.flagConditionField;
        }
        set {
            this.flagConditionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ArrayOfFlagConditionFlagCondition {
    
    private string writeTypeField;
    
    private ArrayOfFlagConditionFlagConditionTargetNote targetNoteField;
    
    private string operatorField;
    
    private string flagsField;
    
    /// <remarks/>
    public string WriteType {
        get {
            return this.writeTypeField;
        }
        set {
            this.writeTypeField = value;
        }
    }
    
    /// <remarks/>
    public ArrayOfFlagConditionFlagConditionTargetNote TargetNote {
        get {
            return this.targetNoteField;
        }
        set {
            this.targetNoteField = value;
        }
    }
    
    /// <remarks/>
    public string Operator {
        get {
            return this.operatorField;
        }
        set {
            this.operatorField = value;
        }
    }
    
    /// <remarks/>
    public string Flags {
        get {
            return this.flagsField;
        }
        set {
            this.flagsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ArrayOfFlagConditionFlagConditionTargetNote {
    
    private byte noteNumField;
    
    /// <remarks/>
    public byte NoteNum {
        get {
            return this.noteNumField;
        }
        set {
            this.noteNumField = value;
        }
    }
}
